### ISSUE TITLE
Hoodling Jumping Higher than Max String Height

### ISSUE THREAD

**Issue by cbrown3** [CornerStoreGames/Hoodlings-0.1#21]
The Hoodling can currently jump higher than the max height of the stationary string, showing the Hoodling as if they were detached, although still attached to the string.

**Comment by cbrown3** [comment]
Make the max height of the Hoodling's jump to be the max height of the stationary string.

**Comment by whenbellstoll** [comment]
Implemented a bounds on the stationary strong, resolving the issue.
