### ISSUE TITLE
Crash After First Jump in Google Play Build

### ISSUE THREAD

**Issue by cbrown3** [CornerStoreGames/Hoodlings-0.1#26]
Game crashes/slows down immediately when jumping on the first jump.

Seems like a memory issue.

**Comment by whenbellstoll** [comment]
Seems to be an issue in PlayerLoop, the profiler indicates there's a huge spike from that process, which also causes spikes in rendering and memory.

**Comment by whenbellstoll** [comment]
The Infinite Level Loader is the source of the issue, but I can't find a way to refactor it that doesn't break other components of the game.

**Comment by cbrown3** [comment]
Removing V-Sync fixed issues with transitioning from Main Menu to Gameplay
